#!/usr/bin/env bash

set -euxo

export shards_file=staging/shards.txt
export model_checkpoint=staging/checkpoint_de2en_best.pt
export output_file=staging/en_de_bt_out
export gpu_device=none
export use_cpu_for_eval=yes
export src_lang=de
export tgt_lang=en
export random_seed=1917
export use_sampling=yes
export dict_en=/tmp/dict.en.txt
export dict_foreign=/tmp/dict.de.txt
export max_tokens=4096
export beam_size=1

bash scripts/translate_sharded_input_with_model \
    $shards_file \
    $model_checkpoint \
    $output_file \
    $gpu_device \
    $use_cpu_for_eval \
    $src_lang \
    $tgt_lang \
    $random_seed \
    $dict_en \
    $dict_foreign \
    $use_sampling \
    $max_tokens
