#!/usr/bin/env bash

set -euxo

export shards_file=staging/shards.txt
export model_checkpoint=staging/checkpoint_de2en_best.pt
export output_file=staging/en_de_bt_out
export gpu_device="0,1"
export use_cpu_for_eval=no
export src_lang=de
export tgt_lang=en
export random_seed=1917
export use_sampling=yes
export dict_en=staging/dict.en.txt.de2en
export dict_foreign=staging/dict.de.txt.de2en
export max_tokens=150000
export beam_size=1

bash scripts/translate_sharded_input_with_model \
    $shards_file \
    $model_checkpoint \
    $output_file \
    $gpu_device \
    $use_cpu_for_eval \
    $src_lang \
    $tgt_lang \
    $random_seed \
    $dict_en \
    $dict_foreign \
    $use_sampling \
    $max_tokens
