name = "en_sp32k_uz_char"
lang_pairs = [ "en-uz",]

[en-uz]
src = "en"
tgt = "uz"
output_base_path = "~/datasets/mrl_nmt22/processed/en-uz/en_sp32k_uz_char"
data_bin_folder = "./data-bin/en-uz/en_sp32k_uz_char"
splits = [ "train", "dev",]

[en-uz.train]
input_base_path = "~/datasets/mrl_nmt22/uz/en-uz"

[[en-uz.train.preprocessing_steps]]
name = "process_uz"

    [en-uz.train.preprocessing_steps.options]
    split = "train"
    en_output_level = "sentencepiece"
    uz_output_level = "char"

        [en-uz.train.preprocessing_steps.options.sentencepiece_config.src]
        vocab_size = 32000
        use_pretrained_model = false
        model_file = "en_sp32k.bin"
        model_base_path = "~/datasets/mrl_nmt22/processed/en-uz/en_sp32k_uz_char"
        input_sentence_size = 5000000
        shuffle_input_sentence = true

[en-uz.dev]
input_base_path = "~/datasets/flores-101/dev"

[[en-uz.dev.preprocessing_steps]]
name = "process_uz"

    [en-uz.dev.preprocessing_steps.options]
    split = "dev"
    en_output_level = "sentencepiece"
    uz_output_level = "char"

        [en-uz.dev.preprocessing_steps.options.sentencepiece_config.src]
        use_pretrained_model = true
        model_file = "en_sp32k.bin"
        model_base_path = "~/datasets/mrl_nmt22/processed/en-uz/en_sp32k_uz_char"
