same = "en_sp32k_vi_sp10k"
lang_pairs = [ "en-vi",]

[en-vi]
src = "en"
tgt = "vi"
output_base_path = "~/datasets/mrl_nmt22/processed/en-vi/en_sp32k_vi_sp10k"
data_bin_folder = "./data-bin/en-vi/en_sp32k_vi_sp10k"
splits = [ "train", "dev",]

[en-vi.train]
input_base_path = "~/datasets/mrl_nmt22/vi/en-vi"

[[en-vi.train.preprocessing_steps]]
name = "process_vi"

    [en-vi.train.preprocessing_steps.options]
    split = "train"
    en_output_level = "sentencepiece"
    vi_output_level = "sentencepiece"
    detokenized_output_path = "~/datasets/mrl_nmt22/processed/en-vi/en_sp32k_vi_sp10k"

        [en-vi.train.preprocessing_steps.options.sentencepiece_config.src]
        vocab_size = 32000
        use_pretrained_model = false
        model_file = "en_sp32k.bin"
        model_base_path = "~/datasets/mrl_nmt22/processed/en-vi/en_sp32k_vi_sp10k"
        input_sentence_size = 5000000
        shuffle_input_sentence = true

        [en-vi.train.preprocessing_steps.options.sentencepiece_config.tgt]
        vocab_size = 10000
        use_pretrained_model = false
        model_file = "vi_sp10k.bin"
        model_base_path = "~/datasets/mrl_nmt22/processed/en-vi/en_sp32k_vi_sp10k"
        shuffle_input_sentence = true

[en-vi.dev]
input_base_path = "~/datasets/mrl_nmt22/vi/en-vi"

[[en-vi.dev.preprocessing_steps]]
name = "process_vi"

    [en-vi.dev.preprocessing_steps.options]
    split = "dev"
    en_output_level = "sentencepiece"
    vi_output_level = "sentencepiece"
    detokenized_output_path = "~/datasets/mrl_nmt22/processed/en-vi/en_sp32k_vi_sp10k"

        [en-vi.dev.preprocessing_steps.options.sentencepiece_config.src]
        use_pretrained_model = true
        model_file = "en_sp32k.bin"
        model_base_path = "~/datasets/mrl_nmt22/processed/en-vi/en_sp32k_vi_sp10k"

        [en-vi.dev.preprocessing_steps.options.sentencepiece_config.tgt]
        use_pretrained_model = true
        model_file = "vi_sp10k.bin"
        model_base_path = "~/datasets/mrl_nmt22/processed/en-vi/en_sp32k_vi_sp10k"
