same = "en_sp5k_iu_sp5k"
lang_pairs = [ "en-iu",]

[en-iu]
src = "en"
tgt = "iu"
output_base_path = "~/datasets/mrl_nmt22/processed/en-iu/en_sp5k_iu_sp5k"
data_bin_folder = "./data-bin/en-iu/en_sp5k_iu_sp5k"
splits = [ "train", "dev",]

[en-iu.train]
input_base_path = "~/datasets/mrl_nmt22/iu/en-iu"

[[en-iu.train.preprocessing_steps]]
name = "process_iu"

    [en-iu.train.preprocessing_steps.options]
    split = "train"
    en_output_level = "sentencepiece"
    iu_output_level = "sentencepiece"

        [en-iu.train.preprocessing_steps.options.sentencepiece_config.src]
        vocab_size = 5000
        use_pretrained_model = false
        model_file = "en_sp5k.bin"
        model_base_path = "~/datasets/mrl_nmt22/processed/en-iu/en_sp5k_iu_sp5k"
        input_sentence_size = 5000000
        shuffle_input_sentence = true

        [en-iu.train.preprocessing_steps.options.sentencepiece_config.tgt]
        vocab_size = 5000
        use_pretrained_model = false
        model_file = "iu_sp5k.bin"
        model_base_path = "~/datasets/mrl_nmt22/processed/en-iu/en_sp5k_iu_sp5k"
        input_sentence_size = 5000000
        shuffle_input_sentence = true

[en-iu.dev]
input_base_path = "~/datasets/mrl_nmt22/iu/en-iu"

[[en-iu.dev.preprocessing_steps]]
name = "process_iu"

    [en-iu.dev.preprocessing_steps.options]
    split = "dev"
    en_output_level = "sentencepiece"
    iu_output_level = "sentencepiece"

        [en-iu.dev.preprocessing_steps.options.sentencepiece_config.src]
        use_pretrained_model = true
        model_file = "en_sp5k.bin"
        model_base_path = "~/datasets/mrl_nmt22/processed/en-iu/en_sp5k_iu_sp5k"

        [en-iu.dev.preprocessing_steps.options.sentencepiece_config.tgt]
        use_pretrained_model = true
        model_file = "iu_sp5k.bin"
        model_base_path = "~/datasets/mrl_nmt22/processed/en-iu/en_sp5k_iu_sp5k"
