name = "en_char_tr_char"
lang_pairs = [ "en-tr",]

[en-tr]
src = "en"
tgt = "tr"
output_base_path = "~/datasets/mrl_nmt22/processed/en-tr/char"
data_bin_folder = "./data-bin/en-tr/char"
splits = [ "train", "dev",]
# splits = [ "dev", ]

[en-tr.train]
input_base_path = "~/datasets/mrl_nmt22/tr/en-tr"

[[en-tr.train.preprocessing_steps]]
name = "process_tr"

    [en-tr.train.preprocessing_steps.options]
    split = "train"
    en_output_level = "char"
    tr_output_level = "char"

[en-tr.dev]
input_base_path = "~/datasets/flores-101/dev"

[[en-tr.dev.preprocessing_steps]]
name = "process_tr"

    [en-tr.dev.preprocessing_steps.options]
    split = "dev"
    en_output_level = "char"
    tr_output_level = "char"
