name = "turkic_bilingual_baseline"

lang_pairs = [
    "en-tr" #, "en-uz"
]

[en-tr]
src = "en"
tgt = "tr"
output_base_path = "~/datasets/mrl_nmt22/processed/en-tr"
splits = ["train", "dev"]

[en-tr.train]
input_base_path = "~/datasets/mrl_nmt22/tr/en-tr"

    [[en-tr.train.files]]
    path = "en-tr.en"
    kind = "src"

        [[en-tr.train.files.preprocessing_steps]]
        name = "read_lines"
        options = {"load_to_memory" = true}

    [[en-tr.train.files]]
    path = "en-tr.tr"
    kind = "tgt"

        [[en-tr.train.files.preprocessing_steps]]
        name = "read_lines"
        options = {"load_to_memory" = true}

[en-tr.dev]
input_base_path = "~/datasets/flores-101/dev"
options = {}

    [[en-tr.dev.files]]
    path = "eng.dev"
    kind = "src"

        [[en-tr.dev.files.preprocessing_steps]]
        name = "read_lines"
        options = {"load_to_memory" = true}

    [[en-tr.dev.files]]
    path = "tur.dev"
    kind = "tgt"

        [[en-tr.dev.files.preprocessing_steps]]
        name = "read_lines"
        options = {"load_to_memory" = true}

# TODO: create Uzbek
