en-vi:
  data_bin_folder: ./data-bin/en-vi/en_sp32k_vi_sp10k
  dev:
    input_base_path: ~/datasets/mrl_nmt22/vi/en-vi
    preprocessing_steps:
    - name: process_vi
      options:
        detokenized_output_path: ~/datasets/mrl_nmt22/processed/en-vi/en_sp32k_vi_sp10k
        en_output_level: sentencepiece
        sentencepiece_config:
          src:
            model_base_path: ~/datasets/mrl_nmt22/processed/en-vi/en_sp32k_vi_sp10k
            model_file: en_sp32k.bin
            use_pretrained_model: true
          tgt:
            model_base_path: ~/datasets/mrl_nmt22/processed/en-vi/en_sp32k_vi_sp10k
            model_file: vi_sp10k.bin
            use_pretrained_model: true
        split: dev
        vi_output_level: sentencepiece
  output_base_path: ~/datasets/mrl_nmt22/processed/en-vi/en_sp32k_vi_sp10k
  splits:
  - train
  - dev
  src: en
  tgt: vi
  train:
    input_base_path: ~/datasets/mrl_nmt22/vi/en-vi
    preprocessing_steps:
    - name: process_vi
      options:
        detokenized_output_path: ~/datasets/mrl_nmt22/processed/en-vi/en_sp32k_vi_sp10k
        en_output_level: sentencepiece
        sentencepiece_config:
          src:
            input_sentence_size: 5000000
            model_base_path: ~/datasets/mrl_nmt22/processed/en-vi/en_sp32k_vi_sp10k
            model_file: en_sp32k.bin
            shuffle_input_sentence: true
            use_pretrained_model: false
            vocab_size: 32000
          tgt:
            model_base_path: ~/datasets/mrl_nmt22/processed/en-vi/en_sp32k_vi_sp10k
            model_file: vi_sp10k.bin
            shuffle_input_sentence: true
            use_pretrained_model: false
            vocab_size: 10000
        split: train
        vi_output_level: sentencepiece
lang_pairs:
- en-vi
same: en_sp32k_vi_sp10k
