en-uz:
  data_bin_folder: ./data-bin/en-uz/en_sp32k_uz_sp4k
  dev:
    input_base_path: ~/datasets/flores-101/dev
    preprocessing_steps:
    - name: process_uz
      options:
        en_output_level: sentencepiece
        sentencepiece_config:
          src:
            model_base_path: ~/datasets/mrl_nmt22/processed/en-uz/en_sp32k_uz_sp4k
            model_file: en_sp32k.bin
            use_pretrained_model: true
          tgt:
            model_base_path: ~/datasets/mrl_nmt22/processed/en-uz/en_sp32k_uz_sp4k
            model_file: uz_sp4k.bin
            use_pretrained_model: true
        split: dev
        uz_output_level: sentencepiece
  output_base_path: ~/datasets/mrl_nmt22/processed/en-uz/en_sp32k_uz_sp4k
  splits:
  - train
  - dev
  src: en
  tgt: uz
  train:
    input_base_path: ~/datasets/mrl_nmt22/uz/en-uz
    preprocessing_steps:
    - name: process_uz
      options:
        en_output_level: sentencepiece
        sentencepiece_config:
          src:
            input_sentence_size: 5000000
            model_base_path: ~/datasets/mrl_nmt22/processed/en-uz/en_sp32k_uz_sp4k
            model_file: en_sp32k.bin
            shuffle_input_sentence: true
            use_pretrained_model: false
            vocab_size: 32000
          tgt:
            model_base_path: ~/datasets/mrl_nmt22/processed/en-uz/en_sp32k_uz_sp4k
            model_file: uz_sp4k.bin
            shuffle_input_sentence: true
            use_pretrained_model: false
            vocab_size: 4000
        split: train
        uz_output_level: sentencepiece
lang_pairs:
- en-uz
name: en_sp32k_uz_sp4k
