name: en_word_fi_word
lang_pairs:
- en-fi
en-fi:
  src: en
  tgt: fi
  corpora:
    - default-train
    - newstest-2018
    - newstest-2019
  default-train:
    output_base_path: ~/datasets/mrl_nmt22/processed/en-fi/en_word_fi_word/default-train
    splits:
    - train
    - dev
    train:
      input_base_path: ~/datasets/mrl_nmt22/fi/en-fi/default-train
      data_bin_folder: ./data-bin/en-fi/en_word_fi_word/default-train
      preprocessing_steps:
      - name: process_fi
        options:
          en_output_level: word
          fi_output_level: word
          split: train
    dev:
      input_base_path: ~/datasets/mrl_nmt22/fi/en-fi/default-train
      data_bin_folder: ./data-bin/en-fi/en_word_fi_word/default-train
      preprocessing_steps:
      - name: process_fi
        options:
          en_output_level: word
          fi_output_level: word
          split: dev
  newstest-2018:
    output_base_path: ~/datasets/mrl_nmt22/processed/en-fi/en_word_fi_word/newstest-2018
    splits:
    - dev
    dev:
      input_base_path: ~/datasets/mrl_nmt22/fi/en-fi/newstest2018
      data_bin_folder: ./data-bin/en-fi/en_word_fi_word/newstest2018
      preprocessing_steps:
      - name: process_fi
        options:
          en_output_level: word
          fi_output_level: word
          split: dev
