name: en_char_fi_char
lang_pairs:
- en-fi

en-fi:
  src: en
  tgt: fi
  corpora:
    - default-train
    - newstest-2018
    - newstest-2019
  default-train:
    output_base_path: ~/datasets/mrl_nmt22/processed/en-fi/en_char_fi_char/default-train
    data_bin_folder: ./data-bin/en-fi/en_char_fi_char/default-train
    splits:
    - train
    - dev
    train:
      input_base_path: ~/datasets/mrl_nmt22/fi/en-fi/default-train
      preprocessing_steps:
      - name: process_fi
        options:
          write_detokenized: true
          detokenized_link_only: true
          detokenized_output_path: ~/datasets/mrl_nmt22/processed/en-fi/en_char_fi_char/default-train
          en_output_level: char
          fi_output_level: char
          split: train
    dev:
      input_base_path: ~/datasets/mrl_nmt22/fi/en-fi/default-train
      preprocessing_steps:
      - name: process_fi
        options:
          write_detokenized: true
          detokenized_link_only: true
          detokenized_output_path: ~/datasets/mrl_nmt22/processed/en-fi/en_char_fi_char/default-train
          en_output_level: char
          fi_output_level: char
          split: dev
  newstest-2018:
    output_base_path: ~/datasets/mrl_nmt22/processed/en-fi/en_char_fi_char/newstest-2018
    data_bin_folder: ./data-bin/en-fi/en_char_fi_char/newstest-2018
    fairseq_src_dict: ./data-bin/en-fi/en_char_fi_char/default-train/dict.en.txt
    fairseq_tgt_dict: ./data-bin/en-fi/en_char_fi_char/default-train/dict.fi.txt
    splits:
    - train
    train:
      input_base_path: ~/datasets/mrl_nmt22/fi/en-fi/newstest-2018
      preprocessing_steps:
      - name: process_fi
        options:
          write_detokenized: true
          detokenized_link_only: true
          detokenized_output_path: ~/datasets/mrl_nmt22/processed/en-fi/en_char_fi_char/newstest-2018
          en_output_level: char
          fi_output_level: char
          split: train  # this "hack" is necessary since
                        # the downloaded files are train.{eng,fin}
  newstest-2019:
    output_base_path: ~/datasets/mrl_nmt22/processed/en-fi/en_char_fi_char/newstest-2019
    data_bin_folder: ./data-bin/en-fi/en_char_fi_char/newstest-2019
    fairseq_src_dict: ./data-bin/en-fi/en_char_fi_char/default-train/dict.en.txt
    fairseq_tgt_dict: ./data-bin/en-fi/en_char_fi_char/default-train/dict.fi.txt
    splits:
    - train
    train:
      input_base_path: ~/datasets/mrl_nmt22/fi/en-fi/newstest-2019
      preprocessing_steps:
      - name: process_fi
        options:
          write_detokenized: true
          detokenized_link_only: true
          detokenized_output_path: ~/datasets/mrl_nmt22/processed/en-fi/en_char_fi_char/newstest-2019
          en_output_level: char
          fi_output_level: char
          split: train  # this "hack" is necessary since
                        # the downloaded files are train.{eng,fin}
