#!/bin/bash
# Evaluates data

set -euo pipefail

# Command line arguments & defaults.
EXPERIMENT_NAME=$1
MODE=$2
BEAM=$3
SEED=$4
GPU_DEVICE=$5
MODEL_NAME=$6
SRC_LANG=$7
TGT_LANG=$8

if [[ -z "${GPU_DEVICE}" ]]; then
	echo "Defaulting to GPU 1..."
	GPU_DEVICE=1
fi

EXPERIMENT_FOLDER="$(pwd)/experiments/${EXPERIMENT_NAME}"
DATA_BIN_FOLDER="${EXPERIMENT_FOLDER}/binarized_data"
CHECKPOINT_FOLDER="${EXPERIMENT_FOLDER}/checkpoints"
EVAL_OUTPUT_FOLDER="${EXPERIMENT_FOLDER}/${MODEL_NAME}"

mkdir -vp $EVAL_OUTPUT_FOLDER

if [[ -z $BEAM ]]; then
	readonly BEAM=5
fi

REMOVE_PREPROCESSING=${9}
CASING=${10}

RAW_DATA_FOLDER="${EXPERIMENT_FOLDER}/raw_data"
RAW_GOLD_DEFAULT="${RAW_DATA_FOLDER}/${SRC_LANG}-${TGT_LANG}.${MODE}.detok.${TGT_LANG}"
RAW_GOLD=${11:-$RAW_GOLD_DEFAULT}

echo "DATA_BIN_FOLDER=${DATA_BIN_FOLDER}"
echo "CHECKPOINT_FOLDER=${CHECKPOINT_FOLDER}"
echo "MODE=${MODE}"
echo "BEAM=${BEAM}"
echo "SEED=${SEED}"
echo "RAW_DATA_FOLDER=${RAW_DATA_FOLDER}"
echo "RAW_GOLD=${RAW_GOLD}"


# Prediction options.

evaluate() {
	local -r DATA_BIN_FOLDER="$1"
	shift
	local -r EXPERIMENT_FOLDER="$1"
	shift
	local -r CHECKPOINT_FOLDER="$1"
	shift
	local -r MODE="$1"
	shift
	local -r BEAM_SIZE="$1"
	shift
	local -r SEED="$1"
	shift
	local -r SRC_LANG="$1"
	shift
	local -r TGT_LANG="$1"
	shift
	local -r RAW_GOLD_FILE="$1"
	shift
	local -r REMOVE_PREPROCESSING="$1"
	shift
	local -r CASING="$1"
	shift

	echo "seed = ${SEED}"

	# Checkpoint file
	CHECKPOINT_FILE="${CHECKPOINT_FOLDER}/checkpoint_best.pt"
	if [[ ! -f "${CHECKPOINT_FILE}" ]]; then
		echo "${CHECKPOINT_FILE} not found. Changing..."
		CHECKPOINT_FILE="${CHECKPOINT_FILE/checkpoint_best/checkpoint_last}"
		echo "Changed checkpoint file to: ${CHECKPOINT_FILE}"
	fi

    # Flag for removing preprocessing
    case "${REMOVE_PREPROCESSING}" in
        "word")
            echo "Outputs are already words!"
            RM_PP_FLAG=""
        ;;
        "none")
            echo "Not removing any preprocessing!"
            RM_PP_FLAG=""
        ;;
        "sentencepiece") 
            echo "Converting outputs from chars to words"
            RM_PP_FLAG="--remove-sentencepiece"
        ;;
        "char") 
            echo "Converting outputs from SP to words"
            RM_PP_FLAG="--remove-char"
        ;;
        *)
            echo "Unrecognized preprocessing type: ${REMOVE_PREPROCESSING}"
            RM_PP_FLAG=""
            exit 1
        ;;
    esac

    # Flag for removing preprocessing
    case "${CASING}" in
        "lower")
            echo "Ignoring casing due to casing=${CASING}"
            CASING_FLAG="--ignore-case"
        ;;
        "ignore")
            echo "Ignoring casing due to casing=${CASING}"
            CASING_FLAG="--ignore-case"
        ;;
        *)
            echo "Unrecognized casing type: ${CASING}"
            echo "Not ignoring case!"
            CASING_FLAG=""
        ;;
    esac

	# Fairseq insists on calling the dev-set "valid"; hack around this.
	local -r FAIRSEQ_MODE="${MODE/dev/valid}"

	OUT="${EVAL_OUTPUT_FOLDER}/${MODE}.out"
	SOURCE_TSV="${EVAL_OUTPUT_FOLDER}/${MODE}_with_source.tsv"
	GOLD="${EVAL_OUTPUT_FOLDER}/${MODE}.gold"
	HYPS="${EVAL_OUTPUT_FOLDER}/${MODE}.hyps"
	SOURCE="${EVAL_OUTPUT_FOLDER}/${MODE}.source"
	SCORE="${EVAL_OUTPUT_FOLDER}/${MODE}.eval.score"

	echo "Evaluating into ${OUT}"

	# Make raw predictions
	CUDA_VISIBLE_DEVICES=$GPU_DEVICE fairseq-generate \
		"${DATA_BIN_FOLDER}" \
		--source-lang="${SRC_LANG}" \
		--target-lang="${TGT_LANG}" \
		--path="${CHECKPOINT_FILE}" \
		--seed="${SEED}" \
		--gen-subset="${FAIRSEQ_MODE}" \
		--beam="${BEAM_SIZE}" \
		--no-progress-bar | tee "${OUT}"


	# Separate gold/system output/source into separate text files
	cat "${OUT}" | grep '^T-' | sed "s/^T-//g" | sort -k1 -n | cut -f2 >"${GOLD}"
	cat "${OUT}" | grep '^H-' | sed "s/^H-//g" | sort -k1 -n | cut -f3 >"${HYPS}"
	cat "${OUT}" | grep '^S-' | sed "s/^S-//g" | sort -k1 -n | cut -f2 >"${SOURCE}"
	
    # Make TSV with source and raw gold included
	paste "${GOLD}" "${HYPS}" "${SOURCE}" "${RAW_GOLD_FILE}" >"${SOURCE_TSV}"

	# Compute some evaluation metrics
	python scripts/evaluate.py \
        --combined-tsv-path "${SOURCE_TSV}" \
		--score-output-path "${SCORE}" \
        ${RM_PP_FLAG} ${CASING_FLAG} \
        --src-language "${SRC_LANG}" \
        --tgt-language "${TGT_LANG}"

	# Finally output the score so Guild.ai grab it
	cat "${SCORE}"
}

evaluate "${DATA_BIN_FOLDER}" "${EXPERIMENT_FOLDER}" "${CHECKPOINT_FOLDER}" "${MODE}" "${BEAM}" "${SEED}"  "${SRC_LANG}" "${TGT_LANG}" "${RAW_GOLD}" "${REMOVE_PREPROCESSING}" "${CASING}"
