en-tr:
  data_bin_folder: ./data-bin/en-tr/en_sp32k_tr_sp32k
  dev:
    input_base_path: ~/datasets/flores-101/dev
    preprocessing_steps:
    - name: process_tr
      options:
        en_output_level: sentencepiece
        sentencepiece_config:
          src:
            model_base_path: ~/datasets/mrl_nmt22/processed/en-tr/en_sp32k_tr_sp32k
            model_file: en_sp32k.bin
            use_pretrained_model: true
          tgt:
            model_base_path: ~/datasets/mrl_nmt22/processed/en-tr/en_sp32k_tr_sp32k
            model_file: tr_sp32k.bin
            use_pretrained_model: true
        split: dev
        tr_output_level: sentencepiece
  output_base_path: ~/datasets/mrl_nmt22/processed/en-tr/en_sp32k_tr_sp32k
  splits:
  - train
  - dev
  src: en
  tgt: tr
  train:
    input_base_path: ~/datasets/mrl_nmt22/tr/en-tr
    preprocessing_steps:
    - name: process_tr
      options:
        en_output_level: sentencepiece
        sentencepiece_config:
          src:
            input_sentence_size: 5000000
            model_base_path: ~/datasets/mrl_nmt22/processed/en-tr/en_sp32k_tr_sp32k
            model_file: en_sp32k.bin
            shuffle_input_sentence: true
            use_pretrained_model: false
            vocab_size: 32000
          tgt:
            input_sentence_size: 5000000
            model_base_path: ~/datasets/mrl_nmt22/processed/en-tr/en_sp32k_tr_sp32k
            model_file: tr_sp32k.bin
            shuffle_input_sentence: true
            use_pretrained_model: false
            vocab_size: 32000
        split: train
        tr_output_level: sentencepiece
lang_pairs:
- en-tr
name: en_sp32k_tr_sp32k
